### ISSUE TITLE
Cannot use 'in' operator to search for 'js' in .jsbeautifyrc

### ISSUE THREAD

**Issue by tayfunyasar** [sorrycc/gulp-jsbeautify#4]
I have an error shown in title.

Here is my gulp task.

Can anyone help about it?

```
gulp.task('beautify', function () {
    return gulp.src(['./app/**/*.html', './app/**/*.js',  '!./app/translate/*'])
        .pipe(
    		beautify('./app/.jsbeautifyrc')
        );
});
```

```[11:26:51] 'beautify' errored after 137 ms
[11:26:51] TypeError: Cannot use 'in' operator to search for 'js' in ./app/.jsbeautifyrc
    at mergeOpts (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/js-beautify/js/lib/beautify.js:119:24)
    at new Beautifier (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/js-beautify/js/lib/beautify.js:323:23)
    at Object.js_beautify (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/js-beautify/js/lib/beautify.js:2459:26)
    at beautify (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/js-beautify/js/index.js:47:28)
    at /Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/gulp-jsbeautify/index.js:11:32
    at wrappedMapper (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/map-stream/index.js:96:21)
    at write (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/myuser/git/myproject/webapps/subproject/project-loyalty-web/src/main/javascript/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

My .jsbeautifyrc file here.

```
{
  "html": {
    "brace_style": "collapse",
    "indent_char": " ",
    "indent_scripts": "normal",
    "indent_size": 6,
    "max_preserve_newlines": 1,
    "preserve_newlines": true,
    "unformatted": ["a", "sub", "sup", "b", "i", "u"],
    "wrap_line_length": 0
  },
  "css": {
    "indent_char": " ",
    "indent_size": 4
  },
  "js": {
    "indent_size": 2,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 2,
    "jslint_happy": true
  },
  "sql": {
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false
  }
}
```

**Comment by tayfunyasar** [comment]
using another gulp task for beautify :)
